services:
  backend:
    build: .
    networks:
      - project
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - MONGO_URI=mongodb://admin:${MONGO_ROOT_PASSWORD}@mongo:27017/iuuIncidents?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongodb/mongodb-community-server:latest
    networks:
      - project
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    networks:
      - project
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

volumes:
  mongo-data:
  qdrant-data:

networks:
  project:
    external: true
