services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      # The backend connects to the 'mongo' service name
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: